### PR TITLE
Update duplicity packages and postgres libraries

### PR DESCRIPTION
**Pull request by joao-p-marques**
Postgresql client should update to latest version on build.
Current latest is version 12.4

This should fix incompatibility problems with Postgresql v13.

TT26463

### CODE REVIEW

**Comment by Yajo** [comment]
According to the build logs, this still has postgres 12.4 libs:

```
#16 [postgres 1/1] RUN apk add --no-cache postgresql
#16 0.247 fetch http://dl-cdn.alpinelinux.org/alpine/v3.12/main/x86_64/APKINDEX.tar.gz
#16 0.361 fetch http://dl-cdn.alpinelinux.org/alpine/v3.12/community/x86_64/APKINDEX.tar.gz
#16 0.510 (1/5) Installing libpq (12.4-r0)
#16 0.528 (2/5) Installing postgresql-client (12.4-r0)
#16 0.567 (3/5) Installing llvm10-libs (10.0.0-r2)
#16 1.078 (4/5) Installing icu-libs (67.1-r0)
#16 1.392 (5/5) Installing postgresql (12.4-r0)
#16 1.406 Executing postgresql-12.4-r0.pre-install
#16 1.797 Executing busybox-1.31.1-r19.trigger
#16 1.805 OK: 174 MiB in 83 packages
#16 DONE 3.7s
```

https://github.com/Tecnativa/docker-duplicity/pull/40/checks?check_run_id=1309826506#step:5:81

**Comment by joao-p-marques** [comment]
Yes, the problem is that v13 packages are not yet available for alpine it seems: https://pkgs.alpinelinux.org/packages?name=postgresql&branch=edge#

Should I try to download the binary?

**Comment by Yajo** [comment]
> Should I try to download the binary?

Yes, that'd be a good solution. Although Alpine is a bit special because it uses musl instead of glibc and there could be incompatibilities. You'll have to complie it instead. You can probably draw inspiration from [the dockerfile of the `postgres:13-alpine` image](https://github.com/docker-library/postgres/blob/04bf35f0c4a3f7ac41591f9b28e2de1fecb7fef4/13/alpine/Dockerfile). Remember to add a TODO to remove all that garbage once postgres 13 packages is available for alpine.

Another option would be to use `postgres:13-alpine` as base image for those flavors and repeat the instructions to install `python3` inside that image and install also duplicity, override the entrypoint, etc.

Any of those approaches is hard, just check which one is easier. I think it'd be the 1st one

**Comment by joao-p-marques** [comment]
I've just pushed changes with you first suggestion. Tested locally and the `postgres` binary becomes available as v13.

**Pull request merged**
