### PR TITLE
Update Dockerfile

### PR DESCRIPTION
**Pull request by pchampio**
Install the docker-cli instead of the full docker-engine.
```log
/ # apk add --no-cache docker-cli
fetch http://dl-cdn.alpinelinux.org/alpine/v3.12/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.12/community/x86_64/APKINDEX.tar.gz
(1/1) Installing docker-cli (19.03.12-r0)
Executing busybox-1.31.1-r19.trigger
OK: 84 MiB in 37 packages


/ # apk add --no-cache docker
fetch http://dl-cdn.alpinelinux.org/alpine/v3.12/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.12/community/x86_64/APKINDEX.tar.gz
(1/10) Installing libseccomp (2.4.3-r0)
(2/10) Installing runc (1.0.0_rc10-r1)
(3/10) Installing containerd (1.3.9-r0)
(4/10) Installing libmnl (1.0.4-r0)
(5/10) Installing libnftnl-libs (1.1.6-r0)
(6/10) Installing iptables (1.8.4-r2)
(7/10) Installing tini-static (0.19.0-r0)(8/10) Installing device-mapper-libs (2.02.186-r1)
(9/10) Installing docker-engine (19.03.12-r0)
(10/10) Installing docker (19.03.12-r0)
Executing docker-19.03.12-r0.pre-install
Executing busybox-1.31.1-r19.trigger
OK: 315 MiB in 47 packages
```

### CODE REVIEW

**Review by joao-p-marques — APPROVED** [review]
Hi! :wave: Thanks for the contribution! :smiley: 

This seems like a good improvement. Just to confirm, have you tested performing updates this way?
Let's see what @Yajo thinks about it.

**Review by Yajo — CHANGES_REQUESTED** [review]
This looks good.

We need a test in docker-flavored images that issues a `docker --version` command and exits with `0`. Do you know how to do that?

**Comment by joao-p-marques** [comment]
Indeed, that would be good 👍Check out the pytest code structure we 
added recently (which, at the moment, only checks if dup was correctly 
installed) and see if you would be able to add a similar test for this 
case. Feel free to ask questions if you need 🙂

**Review by joao-p-marques — CHANGES_REQUESTED** [review]
Thank you for the tests! 

To easily fix the pre-commit errors, you can install it locally with `pre-commit install` and then run it with `pre-commit run -a`. It will also run in each commit from that point on.

**Comment by joao-p-marques** [comment]
oh, I see they are fixed now, nice! :+1:

**Comment by pchampio** [comment]
Yea, sorry for the commits spams -_-.
While I haven't tested the `docker` to `docker-cli` change on this container, I've made this switch on some of my other container, and it has been working well!

**Comment by joao-p-marques** [comment]
I am thinking the tests might fail, though, as you need to pass the docker socket to the container and mark it as privileged. You may need to change [the `container()` contextmanager](https://github.com/Tecnativa/docker-duplicity/blob/master/tests/conftest.py#L36) to add that option when creating the container.

**Comment by joao-p-marques** [comment]
> I am thinking the tests might fail, though, as you need to pass the docker socket to the container and mark it as privileged. You may need to change the container() contextmanager to add that option when creating the container.

Oh, never mind, as we are only checking the version, I see that they pass. 
@Yajo WDYT?

**Review by joao-p-marques — APPROVED** [review]

**Comment by joao-p-marques** [comment]
@pchampio could you squash the commits related to the test updates in 1?

**Comment by Yajo** [comment]
Don't worry, we can squash on merge.

**Review by Yajo — APPROVED** [review]

**Comment by pchampio** [comment]
Don't forget to update the container on Docker hub ;)
Thanks for your work, `docker-duplicity` is awesome!

**Comment by Yajo** [comment]
It should have been done automatically on merge.

**Pull request merged**
